### ISSUE TITLE
Overly sensitive accept header parsing

### ISSUE THREAD

**Issue by pdylanross** [moonclerk/developer#2]
I've just started working on a small C# WPF app for a buddy so he can easily pull up info on his cutomers in exchange for free tea. I found that if you put a space after the semicolon in the accept header it'll break the api, with the error `Endpoint /customers not found for API v(Unknown).`

So, `Accept: application/vnd.moonclerk+json; version=1` breaks it, whereas `application/vnd.moonclerk+json;version=1` is fine. 

This is an issue because in C# the accept headers are generated automatically by the HttpClient class and you can't just add the line to the request. 

Also, as a sidenote, you should return total counts for any paginated requests in the return headers, so I can paginate on my end without having to fetch all of the entries just to get a count for total number of pages, etc.

**Comment by ryanwood** [comment]
@pdylanross Thanks for the heads up. Since this is just our documentation site I'm going to close this issue but will pass it along to the dev team to make the header a little more forgiving.

**Comment by mbbertino** [comment]
@pdylanross Wanted to let you know we've just pushed a fix that loosens the requirements in api accept headers.
