### ISSUE TITLE
Total record count

### ISSUE THREAD

**Issue by markgandolfo** [moonclerk/developer#4]
Hi, 

It's necessary to understand how many records come back from a query to determine if I need to paginate to the next set. 

i.e.

    { 
        'count': 100, 
        'current_offset': 0,
        'total': 1000,
        'payments': [ 
            {}, {}, {}
         ]
    }

This tells me I have 1000 products given the current search query, and that my current offset (position) starting at 0, and that I'm counting by 100... I can then quickly work out where I am in the collection and if I'm at the end. 

Right now, I'm having to do an extra query to work out if I've got an empty result..

**Comment by ryanwood** [comment]
Hey @markgandolfo. We purposely don't do an extra query for the total count as it will double the number of queries that our API servers need to perform and there are pretty simple work arounds. 

I would recommend checking the number of records returned in the current page. If it's less than the page size then you know you are at the end of the road. On the very edge case that you have an exact match (page size 50 and 50 records returned) you would need to handle 0 records found on the next call.

While not a perfect solution, it should work well in most cases. Thanks for the feedback.

**Comment by markgandolfo** [comment]
Thanks Ryan, 
a good solution. It would be handy though to have that extra meta information on the response from any API call that returns a collection, it feels like that would be a much more robust system, over counting the number of returned records. 

Thanks
