### ISSUE TITLE
Adding activities into API

### ISSUE THREAD

**Issue by ryanfinke** [moonclerk/developer#9]
Can you add activity data into the API? We want to build a custom email notification system which would alert one of our staff when a change has been made to a plan (e.g. plan amount has been increased or decreased). 

e.g. https://app.moonclerk.com/plans/123123/activities

**Comment by ryanwood** [comment]
Hey @ryanfinke. That would be more along the lines of adding a webhook infrastructure which we currently do not support. 

Instead, we recommend that you leverage [Stripe webhooks](https://stripe.com/docs/webhooks) to [listen for the events](https://stripe.com/docs/api#event_types) that you are interested in and then look up any relevant data via the MoonClerk API. Hope that helps.
